name: Build Docker Image

on:
  push:
    tags:
      - v*

jobs:
  # Push image to Package Registries (ghcr.io and DockerHub).
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry (DockerHub)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Log into registry (ghcr.io)
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}
          
      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: |
            vasilev/clojurescript
            ghcr.io/vasilev/clojurescript
            
      - name: Debug Print metadata
        run: echo "${{ steps.metadata.outputs }}"

      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
